server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8

spring:
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss

  ## 加载多个配置文件
  profiles:
    active: github,jdbc

  thymeleaf:
    encoding: UTF-8
    ## 开发时关闭缓存功能
    cache: false






  ## 设置session过期时间
  session:
    timeout: 3000
  jackson:
    date-format: purple.sakura.community.config.ChinaTimeFormat
    time-zone: GMT+8


# fastjson

