spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: "alice"
      password: "0000"
      url: "jdbc:mysql:///community?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8"
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 10
      max-wait: 3000

mybatis:
  type-aliases-package: purple.sakura.community.pojo
#  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: purple.sakura.community.config

