server:
  port: 80

spring:
  mvc:
    format:
      date: yyyy-MM-dd


  jackson:
    date-format: purple.sakura.community.config.ChinaTimeFormat

  # 静态资源



#  spring.resources.static-locations= classpath:/static        //此配置为静态资源的真实路径
#  spring.mvc.static-path-pattern=/resources/static/**        //此配置为访问静态资源的url配置